project:
  type: book
  output-dir: docs
book:
  title: "diary"
  author: "Norah Jones"
  date: "2024/1/23"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo, flatly]
        dark: [cosmo, darkly]
  pdf:
    documentclass: scrreprt

editor: visual

